# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models


class LoadtestLinkedMixin(models.AbstractModel):
    """Link a generated record to the batch that owns it. A plain indexed
    many2one instead of a relation table: cleanup and counting stay
    cheap at millions of records, and a batch never has to load the ids
    of everything it generated."""

    _name = "loadtest.linked.mixin"
    _description = "Load Test Batch Link"

    loadtest_batch_id = fields.Many2one(
        "loadtest.batch",
        string="Load Test Batch",
        index=True,
        ondelete="set null",
        copy=False,
        help="Generated by this load-test data batch",
    )


class ResPartner(models.Model):
    _name = "res.partner"
    _inherit = ["res.partner", "loadtest.linked.mixin"]


class ProductTemplate(models.Model):
    _name = "product.template"
    _inherit = ["product.template", "loadtest.linked.mixin"]


class SaleOrder(models.Model):
    _name = "sale.order"
    _inherit = ["sale.order", "loadtest.linked.mixin"]
